### ISSUE TITLE
How to package this project

### ISSUE THREAD

**Issue by douglascrp** [keensoft/alfresco-firma-pdf#2]
Hey.

I'm trying to build this project from sources, but if I simply follow the steps and run mvn clean package, the share's amp is incomplete.
How are you guys including the mini-applet.jar into the amp?

If I take your amp and extract its content, I see this:

sign-document-share-0.8.0/root/sign/miniapplet-full_1_2.jar

I coun't find any dependency declared into pom.xml files.

I also tried to get that applet's jar from these projects:
http://svn-ctt.administracionelectronica.gob.es/svn/clienteafirma/
and
https://github.com/ctt-gob-es/clienteafirma

But got no success so far.

I hope I can get some help from you.

**Comment by angelborroy** [comment]
.gitignore was skipping .jar files from commits

JAR file for miniapplet has been restored.

If you perform an "mvn clean" on https://github.com/ctt-gob-es/clienteafirma you get miniapplet-full.jar at /clienteafirma/afirma-ui-miniapplet-deploy/src/main/webapp path

**Comment by douglascrp** [comment]
Thank you so much @angelborroy 
I'm going to try your solution right now.
