### ISSUE TITLE
Loading signature component, please accept every security alert 

### ISSUE THREAD

**Issue by dongovor** [keensoft/alfresco-firma-pdf#3]
Hi. I've installed amps (repo and share) and trying to sign some pdf file, but always see window with message "Loading signature component, please accept every security alert " . No alerts are showing. Tested with latest chrome, mozilla.

**Comment by angelborroy-ks** [comment]
Our component is based on an Applet. Please, review requirements in order tu run an Applet in a browser: https://java.com/en/download/help/enable_browser.xml

**Comment by dongovor** [comment]
Thanks for the answer. I forgot about this...shame on me((( All works fine now.
